language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
before_script:
  - npm prune
after_success:
  - npm run report-coverage
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: /dist
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
